### ISSUE TITLE
Can't connect to telnet

### ISSUE THREAD

**Issue by dromer** [Theliel/Xiaomi-Mijia-4K#1]
Thank you for this documentation! it has been a very good resource.

The only problem I'm getting is that I can't connect over telnet. I put an empty ```telnet.txt``` file on the sdcard root, but I just get:
```
$ telnet 192.168.42.1 23
Trying 192.168.42.1...
telnet: Unable to connect to remote host: Connection refused
```

Any ideas? Version info:
```
NAME: MI ACTION CAMERA 4k
MODEL: YDXK01FM
VERSION V0.6.11.05
```

ps;
I'm also wondering if it is possible to get the camera to connect to a local wifi AP instead of starting it's own AP.

**Comment by Theliel** [comment]
Yes, its very possible (and easy) to connect to a home AP. If i have some time, i will update and upload some scripts.

Telnet should work fine, try in the first 60-120seg

**Comment by dromer** [comment]
Thank you for the fast reply.

I managed to update the firmware to ```V0.6.15.05``` and I can get a telnet shell now.
Rummaging on the filesystem I found the wireless scripts and that on the sdcard one needs a ```MISC/wpa_supplicant.conf``` but I don't know yet how to put the cam in to STA-mode.

Looking forward to your updates :)

**Comment by dromer** [comment]
Did you find time for those scripts?
I haven't been able to connect to my home AP yet.

**Comment by dromer** [comment]
Revisiting this project, but I still haven't found out how to let the camera connect to an AP.
Any tips? :)

**Comment by Theliel** [comment]
When i have some time, i will update some scirpts, and add how to use our camera in AP mode, is easy :).

**Comment by dromer** [comment]
Looking forward to it!

**Comment by ste-giordano95** [comment]
Hi @Theliel  i do live rtsp but after a few seconds the room WiFi goes off... any solution? Thank you!

**Comment by dromer** [comment]
@Steppdroid it's ok to open a new issue for that. Nobody will bite you when you do.

**Comment by Theliel** [comment]
@dromer script for WIFI AP mode have been uploaded

**Comment by dromer** [comment]
Fantastic @Theliel !

So to be clear:
The ```wifi_ap_template.conf``` should be placed on the sd card under ```MISC/wifi.conf``` and for it to be used there must be the ```wifi_ap_mode.ash``` placed on the sd card as ```autoexec.ash```.
If wifi is configured as ```AUTO ON``` the camera will auto-connect to the AP.

**Comment by dromer** [comment]
(this btw does not work for me. I still see the ```MiCam_******``` network)

**Comment by Theliel** [comment]
exactly.

wifi_ap_template.conf renamed to wifi.conf -> SDRoot/MISC/
wifi_ap_mode.ash renamed to autoexec.ash -> SDRoot/

wifi.conf edited with your WIFI settings (SSID/password), password or SSID in straight form, example:
ESSID=Imthebest
PASSWORD=aabbccddeeff0011

**Comment by Theliel** [comment]
Ops, i forgot it, remember always maintain linux end of line style, not windows. (use for example notepad++ and make sure linux EOL si selected.)

**Comment by dromer** [comment]
I .. don't know what that means. I used mousepad to edit these files. (ie. I am on linux)

The 'ash' script, should the lines end with ```;``` ?

**Comment by dromer** [comment]
Ok, I added an extra newline in vim, and now it seems to work :D

**Comment by ste-giordano95** [comment]
Nice, thank u! @Theliel  You can get a live video from micro usb? like this video "TV OUT ON" https://www.youtube.com/watch?v=2dHdhbEZEl4

**Comment by dromer** [comment]
Please open a new issue @Steppdroid 

I should've closed this one ages ago.

**Comment by davepee** [comment]
Hello, thank you for your developement.  I am trying to connect to telnet but on fw V0.6.16.02i not working. Connection refused.

**Comment by Theliel** [comment]
Im on Firmware 0.6.14.02, but should work fine on V0.6.16.02i

**Comment by davepee** [comment]
OK, but where could be a problem?

`-rwx------ 1 davepee Domain Users    627 led 19 18:49 autoexec.ash
-rwx------ 1 davepee Domain Users    493 led 19 17:54 autoexec.ash.AP
-rwx------ 1 davepee Domain Users      0 led 19 17:31 bsa_server.log
-rwx------ 1 davepee Domain Users      0 led 19 17:31 btsnoop.cfa
drwx------ 1 davepee Domain Users 131072 led 18 16:34 DCIM
drwx------ 1 davepee Domain Users 131072 led 19 17:54 MISC
-rwx------ 1 davepee Domain Users      0 led 19 17:55 telnet.txt
`
Of course I am connected on camera AP.
